[tool.isort]
profile = "black"
multi_line_output = 3
src_paths = ["webhook_catcher"]
remove_redundant_aliases = true
line_length = 120

[tool.black]
line-length = 120
target-version = ['py38']
exclude = '/(\.idea|\.eggs|\.git|\.hg|static|\.mypy\_cache|\.nox|\.tox|\.venv|venv|_build|buck-out|build|dist|configs|docker|.+\.egg-info|\.pytest_cache)/'
